title: "Wesley Zajicek"
site_name: "wesleyzajicek.com"
public-url: "https://wesleyzajicek.com" ## This gets generated into the link that displays in the footer (the one above the social icons)
url: 'https://wesleyzajicek.com' ## NO TRAILING SLASHES!!/<--nope
timezone: America/Chicago
google-tag_key: Google Tag Manager key goes here
translate: true ## Uncomment to activate Google Translate Powers!!
og_title: WelseyZajicek.com
og_type:
og_url: https://wesleyzajcek.com
og_iamge:
source: _pages/
nav_links:
  - link_text: Home
    link_href: ''
    button: false
  - link_text: Landing Page
    link_href: 'landing-page'
    button: false
  - link_text: Accordion
    link_href: accordion
    button: false
collections:
  contacts:
    output: false
  accordions:
    output: false
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    title: ''
    permalink: /:categories/:title/
    baseurl: ../../../
permalink: pretty
email:
description: "Wesley Zajicek - Web Development"
baseurl: "/" # the subpath of your site, e.g. /blog
include:
   - "_posts"
   - "_pages"
# include future posts? (true or false)
future: false
# Build settings
markdown: kramdown
exclude:
  - "gulpfile.js"
  - "gulp-tasks/"
  - "node_modules"
  - "npm-debug.log"
  - "package.json"
  - "package-lock.json"
  - "README.md"
  - "Gemfile"
  - "Gemfile.lock"
  - "gulpconfig.yml"
  - "webpack.config.js"
  - "install.sh"
  - "install_template.sh"
  - "WEBPACK-BABEL-COREJS_INFO.md"
  - "siteicon.png"
  - "page-startups"
  - "UPDATE_PROCEDURE.md"
  - "ruby-version.txt"